print("Tämä ohjelma laskee suorakulmion piirin ja pinta-alan.\nAnna kanta ja korkeus, ole hyvä.")
kanta_str = input("Kanta: ")
korkeus_str = input("Korkeus: ")
kanta = float(kanta_str)
korkeus = float(korkeus_str)
piiri = float(kanta*2+korkeus*2)
pinta_ala = float(kanta*korkeus)
print(f"Piiri: {piiri}")
print(f"Pinta: {pinta_ala}")