print("Tämä ohjelma laskee kolmen luvun summan, tulon ja keskiarvon.\nAnna kolme lukua, kiitos.")
luku1_str = input("ensimmäinen numero: ")
luku2_str =input("toinen numero: ")
luku3_str = input("kolmas numero: ")
luku1 = float(luku1_str)
luku2 = float(luku2_str)
luku3 = float(luku3_str)
print(f"Summa: {luku1 + luku2 + luku3}")
print(f"Tulo: {luku1 * luku2 * luku3}")
print(f"Keskiarvo: {(luku1 + luku2 + luku3) / 3}")

